#!/usr/bin/env python3
"""Turn `git log` + diff for a release window into human-readable release notes.

Usage:
  release_notes.py <input_file>

The input file should contain commit list + diffstat + a truncated patch.
Stdout: markdown notes ready for `gh release create --notes-file`.
Always exits 0 — degrades to a sensible fallback if the API call fails.
"""

from __future__ import annotations

import sys

from _claude_api import DEFAULT_MODEL as MODEL
from _claude_api import call_claude

MAX_INPUT_CHARS = 80_000


def build_prompt(content: str) -> str:
    return f"""You are writing release notes for the Shortlink demo
(FastAPI + Vite/React/TS, deployed to Fly.io). Below is the commit log,
diffstat, and a truncated patch covering the changes since the previous
release.

Write release notes in this exact markdown shape:

## Highlights
2–4 short bullets covering the user-visible / behavior-changing items.
Skip pure refactors and chore commits unless they're notable.

## What changed
Optional grouped lists if there's variety:
- **Frontend** — bullets
- **Backend** — bullets
- **CI / Infra** — bullets

## Notes for operators
Any breaking changes, env var additions, or migrations the operator
should know about. Skip the section entirely if there's nothing.

Write tightly. No marketing fluff. Past tense. Reference commit shorts
(`abc1234`) where it adds clarity. Do not invent features that aren't in
the diff.

Input:
```
{content[:MAX_INPUT_CHARS]}
```
"""


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: release_notes.py <input_file>", file=sys.stderr)
        return 2

    content = open(sys.argv[1]).read()
    if not content.strip():
        print("## Release\n\nNo changes since last release.")
        return 0

    try:
        text = call_claude(build_prompt(content))
    except Exception as e:
        # Fallback: just emit the commit list.
        print("## Release\n")
        print("_AI summary unavailable; raw commit list below._\n")
        print("```")
        print(content[:4000])
        print("```")
        print(f"\n<sub>error: `{type(e).__name__}: {e}`</sub>")
        return 0

    print(text)
    print(f"\n<sub>Generated by Claude · model `{MODEL}`</sub>")
    return 0


if __name__ == "__main__":
    sys.exit(main())
